<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RulesAndRegulationsForm extends Model
{
    use HasFactory;

    protected $fillable = [
        'rule1',
        'rule2',
        'rule3',
        'rule4',
        'rule5',
        'rule6',
        'rule7',
        'rule8',
        'rule9',
        'rule10',
        'rule11',
        'rule12',
        'rule13',
        'rule14',
        'rule15',
        'rule16',
        'rule17',
        'rule18',
        'rule19',
        'rule20',
        'rule21',
        'rule22',
        'rule23',
        'rule24',
        'rule25',
        'rule26',
        'rule27',
        'rule28',
        'rule29',
        'rule30',
        'rule31',
        'rule32',
        'rule33',
        'rule34',
        'rule35',
        'rule36',
        'signed',
        'date',
    ];

    protected $attributes = [
        'rule1' => null,
        'rule2' => null,
        'rule3' => null,
        'rule4' => null,
        'rule5' => null,
        'rule6' => null,
        'rule7' => null,
        'rule8' => null,
        'rule9' => null,
        'rule10' => null,
        'rule11' => null,
        'rule12' => null,
        'rule13' => null,
        'rule14' => null,
        'rule15' => null,
        'rule16' => null,
        'rule17' => null,
        'rule18' => null,
        'rule19' => null,
        'rule11' => null,
        'rule20' => null,
        'rule21' => null,
        'rule22' => null,
        'rule23' => null,
        'rule24' => null,
        'rule25' => null,
        'rule26' => null,
        'rule27' => null,
        'rule28' => null,
        'rule29' => null,
        'rule30' => null,
        'rule31' => null,
        'rule32' => null,
        'rule33' => null,
        'rule34' => null,
        'rule35' => null,
        'rule36' => null,
        'signed' => null,
        'date' => null,
    ];
}
